import { Product, ProductsQuery, ProductsResponse } from "../types/product";

/* ─────────────────────────────────────────────────────
   Khi tích hợp API thật, thay mock bằng:

   export async function getProducts(query?: ProductsQuery): Promise<ProductsResponse> {
     const params = new URLSearchParams();
     if (query?.category) params.set("category", query.category);
     if (query?.sort)     params.set("sort", query.sort);
     if (query?.page)     params.set("page", String(query.page));
     if (query?.limit)    params.set("limit", String(query.limit));

     const res = await fetch(
       `${process.env.API_URL}/products?${params}`,
       { next: { revalidate: 60 } }        // ISR — cache 1 phút
     );
     if (!res.ok) throw new Error("Failed to fetch products");
     return res.json();
   }
───────────────────────────────────────────────────── */

const MOCK_PRODUCTS: Product[] = [
  { id: "p-001", slug: "merino-cloud-throw",      name: "Merino Cloud Throw",      priceInCents: 42000, currency: "USD", material: "100% Organic Merino Wool",          category: "Throws",   categorySlug: "throws",   badge: "New",        isAvailable: true, createdAt: "2025-01-15T00:00:00Z", imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuC4fDkx8a6xYLVZrRiMOId4mF9qOq_A6fb_gZLAkgYxos3woUfgqxc9_-caD7rEhCOf7dJV9txBqLzadiIbPZzwGRYocTtE856u0HkFybIMq4b3ClwHv98Dz3rh4JA3RTqUIywoAAHKRfxW4Noai-_ehXQT40E-gh03d3Ri1JAZNh3Fbjy97pWBa2cX9mVeT_t7QFj3FSZVmN2olDS40wEAQz6rHopzUelWVU80kBD_4fgXBaMQgemF9Iau0of9qyoE4GHX1IYvrwo" },
  { id: "p-002", slug: "cable-knit-cushion",      name: "Cable Knit Cushion",      priceInCents: 18500, currency: "USD", material: "Handmade Cotton Blend",             category: "Cushions", categorySlug: "cushions",                      isAvailable: true, createdAt: "2024-11-02T00:00:00Z", imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuDrsTbIhr8VvkPxrnjcxquP0h6K_2WPvrrqwJZmQkL_yNNjGHNhZ5SvlqKOx7NRPo1enduCnxdWgiRkxfJlpe0R1XFA_YFSm3ffj2mBBON99lgU2vInM9OqxMlf2ctat-_IZzvmvYUOdcTVZErwN11lpQnHJ54BKicGYZrE2DNUkbv9wUma2u_gi4_O4yRhdELd7btgjFvVIo5fFoOKjAvJYmDSJ3hWsQMhVE7bQ91oUXzsdeDk22kHwu9Z3G32N-xLciRk4yN21BM" },
  { id: "p-003", slug: "oatmeal-texture-rug",     name: "Oatmeal Texture Rug",     priceInCents: 89000, currency: "USD", material: "Woven Alpaca Wool",                 category: "Rugs",     categorySlug: "rugs",     badge: "Bestseller", isAvailable: true, createdAt: "2024-09-20T00:00:00Z", imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuBmgYnlGiANqFRA7kNvb3eNWBz4zSd9VSmssbt1FbOhRAMpgoMfNFY0rds3pFhKrKYcMYuZKCDTbDZupKaaLbJ839TpJ88T2lkuBnQCQnItiHrTt_XT3B2_yXyzS0OvrcXJGtJ2Jvlhx6NKbO9Gb7enJvlqB6Man-eVWJHZPxgdPNYP48_GY1J5eK0QlJLOdGs458rTarp2XNaDFgpf98BeG2bwQLXNbQ__DYdLZxxyhwEjh36AWMUAxa_BvQFtagl_AK7GcPbcytw" },
  { id: "p-004", slug: "silk-wool-wrap",          name: "Silk & Wool Wrap",        priceInCents: 31000, currency: "USD", material: "Limited Edition",                   category: "Throws",   categorySlug: "throws",   badge: "Limited",    isAvailable: true, createdAt: "2024-12-01T00:00:00Z", imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuBXutQduBS1tDGHWgkeI-oNYfPrZbF1EcgCHRUVf7uybtvdACqtdcr0_rs-toohEZoYDKjr4eYKNaeVxmIYtIG4YvdDdK9YCiISt_GuM4qSqPiC-6fACFe4sAYTVAHbZfIimdzAx6g652YyoIuj9ExfcS7GDSVuuyC6EcdmpjOgGJ4O71E10WFOt7Ly9FJWiqWVcO1L09CK6xVbqeUjPGVuejbiC162dZuJbHUsdT5gA1hb-QKrSIsJeQXg1q1k_NqS0W3PHcV80SE" },
  { id: "p-005", slug: "ivory-boucle-throw",      name: "Ivory Boucle Throw",      priceInCents: 38000, currency: "USD", material: "Boucle Wool Blend",                 category: "Throws",   categorySlug: "throws",                        isAvailable: true, createdAt: "2024-10-10T00:00:00Z", imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuAp9f1M64Xn7ehv8vs-TAgqDSR854VE8LHranmPKuNVm6ESk_mKMjaTb9miR_DPQGVeOhhsQ9rHyXIZUUfmukmNAZuMEwTvloUZqVPp3X0D_PIKS5exY7qJhdZiwu_a07r9ACRCrKnLOAhvAXzGurkvrE2mjy3LMBHSxqY0ZLV-yiv6l2zU9P6TkaKRJJM5hPbe3XIa8VfJUkpbb52XHbGLw3IqHLnpI3h_exNYbzJ4r50MheTYP7fwtH0hN4KkVhZBoXb5iNwBMy0" },
  { id: "p-006", slug: "velvet-accent-cushion",   name: "Velvet Accent Cushion",   priceInCents: 14500, currency: "USD", material: "Belgian Velvet",                    category: "Cushions", categorySlug: "cushions", badge: "New",        isAvailable: true, createdAt: "2025-01-28T00:00:00Z", imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuBaqKjN_qh9_nvQStIndooZykKBPFIim30BT6jUiHDGxWPI40md4zPo3vwNFFWaEejLoVNETFblDSCgkjEgZuzQrEFNx4mrLWlHzpM8ATY3sff2LxnyjFYblIaQM3phvQXVH9V_nMyl2XslpRB8r2s1ne9ONmpYf1vbwPAejPs6ozB8KjZ3mlheOM1QhLJSeUpI4Tc0uGKfXSaiC3_7zbwN8Pnv1MaIR6l2KMIQR_IqY7BKJtTk-Qb6jZ05PgJPf0Jp5rZ_dl3_sOQ" },
  { id: "p-007", slug: "heritage-wool-rug",       name: "Heritage Wool Rug",       priceInCents: 120000, currency: "USD", material: "Hand-knotted New Zealand Wool",   category: "Rugs",     categorySlug: "rugs",                          isAvailable: true, createdAt: "2024-08-05T00:00:00Z", imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuAN75cqxoSnhOSjO4x7bkbnHaMOeVwOsVI2rDDFN6Xo8P4AWT7gpLr5CgwenyBEPKGEMnaCXjItzunkUdrbotuuQnZKj8-lUEIJu7T5PMfNAiEP1CCYb-R0wr4F8kDzvkG3LPnHao_CapK5mSzEm7bkZuRpUWSM5KZ5Ug0VKFGQLT8yMkeZ0FkHYJFzjzrOyY5xMt7QV2tDH97M9yr_LjvfHSUZ71VAskXnyfav2RTrSaybayD66pJ-2GOtFdQl2pyp5wBv2ott-oM" },
  { id: "p-008", slug: "cashmere-travel-wrap",    name: "Cashmere Travel Wrap",    priceInCents: 56000, currency: "USD", material: "Grade-A Mongolian Cashmere",        category: "Throws",   categorySlug: "throws",   badge: "Bestseller", isAvailable: true, createdAt: "2024-07-18T00:00:00Z", imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuAtJuPF37gE56fSewtifGK_tM7K5o-bpW354TJuzcbvCFdmiBIOZOE00Aqm26uOuxB_A9twsMVl_sgtQXBjB9uzwwKx9UBmzIbtPWm6Np1aDakw8sn5tdTFXedkDV61QToyFY5cLv6_TWSGXHBJeNg1gkyAlHltaGtYhjuTsvz7YUTtIuOFVcPbnOU_k5rc5KkA1T4jMcSGIu6MPAcPzO0tgjzkYrAI5knKGJhFEhC296icFQmHGDnLsSGU5gejYs0U3bovKmu3Btw" },
  { id: "p-009", slug: "linen-weave-cushion",     name: "Linen Weave Cushion",     priceInCents: 16500, currency: "USD", material: "European Stonewashed Linen",        category: "Cushions", categorySlug: "cushions",                      isAvailable: true, createdAt: "2024-10-30T00:00:00Z", imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuCUqBJh2dv8H2MeJxXuFow45okAbswrol6Q18bUEmdhWcTXLr5nrndXL8jl8sc9aDWTI_83itlul8p80-yDtjXKti3AgO95D2Kv5rCgpYP2mxSrPbE4De5F1o83DesDIGfwdRj34vcdJ3THJf9WbKRmROFoN6yS1CsMHTfo_I1dkpsu8GxN5qu0-LW4SG7bifXsDkdDzDJ9rPd3QQBbLmAK8agVYq6DpLvWjwrWBGy5qUgDxeb5IOjIqQYLFYiyso5fKAaQ9Gk-puA" },
  { id: "p-010", slug: "jute-wool-runner",        name: "Jute & Wool Runner",      priceInCents: 34000, currency: "USD", material: "Natural Jute & Merino",            category: "Rugs",     categorySlug: "rugs",     badge: "Limited",    isAvailable: true, createdAt: "2024-11-22T00:00:00Z", imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuBKl2gqJxZcC51zFxd4XwvCdmbVroEMa0h267Z5Zf5xq00sRgN5rPBDq5ZXYLD1nm_Dbz6iHRQokMijSrP3RLikKbc0TQIO4aVucKqUXkfCUOBCNefiwjuYEZh8aK_Pr5cssMFFYGsQUx5pySvF8CP1mkcAHwNmaB1JGSa7jHL2BCicti0BHtJUILJ0FEpY0KlPWIJJKRcrbXeUP0DwqyefUybKhHZjL3polR8I1o6XnbxWwUneJIabwj5Z1tP8t4ybwIV5LsF6rkU" },
  { id: "p-011", slug: "alpaca-chunky-throw",     name: "Alpaca Chunky Throw",     priceInCents: 49000, currency: "USD", material: "100% Baby Alpaca",                 category: "Throws",   categorySlug: "throws",   badge: "New",        isAvailable: true, createdAt: "2025-02-01T00:00:00Z", imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuB5P5jfL6RURg_w2_8tlxOjWh9aticf_LV17dMSblStiJkWbohjoEEACUR93dhAHngGT5YKnnRmiNsV6r9HRN2sO21tU7c-_MCddiLVnFm0oXQ8OgX3TVbGajCSR3aR1reX1UcULVdlOyLGOcfyXUpR5AgIYSfwqjhNYVEay62Njg_xWkR-3gwtcVFVscaKvDz6KLdA4oAy1-jZWD6L-imGnBmDMA1aLG8lUEJ7f8wJtXFcj6ztEQesDX6xP40PxSYRlZkKBKXy0dc" },
  { id: "p-012", slug: "fringed-cotton-cushion",  name: "Fringed Cotton Cushion",  priceInCents: 12000, currency: "USD", material: "Hand-tufted Cotton",               category: "Cushions", categorySlug: "cushions",                      isAvailable: true, createdAt: "2024-09-05T00:00:00Z", imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuC4fDkx8a6xYLVZrRiMOId4mF9qOq_A6fb_gZLAkgYxos3woUfgqxc9_-caD7rEhCOf7dJV9txBqLzadiIbPZzwGRYocTtE856u0HkFybIMq4b3ClwHv98Dz3rh4JA3RTqUIywoAAHKRfxW4Noai-_ehXQT40E-gh03d3Ri1JAZNh3Fbjy97pWBa2cX9mVeT_t7QFj3FSZVmN2olDS40wEAQz6rHopzUelWVU80kBD_4fgXBaMQgemF9Iau0of9qyoE4GHX1IYvrwo" },
  { id: "p-013", slug: "merino-cloud-throw",      name: "Merino Cloud Throw",      priceInCents: 42000, currency: "USD", material: "100% Organic Merino Wool",          category: "Throws",   categorySlug: "throws",   badge: "New",        isAvailable: true, createdAt: "2025-01-15T00:00:00Z", imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuC4fDkx8a6xYLVZrRiMOId4mF9qOq_A6fb_gZLAkgYxos3woUfgqxc9_-caD7rEhCOf7dJV9txBqLzadiIbPZzwGRYocTtE856u0HkFybIMq4b3ClwHv98Dz3rh4JA3RTqUIywoAAHKRfxW4Noai-_ehXQT40E-gh03d3Ri1JAZNh3Fbjy97pWBa2cX9mVeT_t7QFj3FSZVmN2olDS40wEAQz6rHopzUelWVU80kBD_4fgXBaMQgemF9Iau0of9qyoE4GHX1IYvrwo" },
  { id: "p-014", slug: "cable-knit-cushion",      name: "Cable Knit Cushion",      priceInCents: 18500, currency: "USD", material: "Handmade Cotton Blend",             category: "Cushions", categorySlug: "cushions",                      isAvailable: true, createdAt: "2024-11-02T00:00:00Z", imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuDrsTbIhr8VvkPxrnjcxquP0h6K_2WPvrrqwJZmQkL_yNNjGHNhZ5SvlqKOx7NRPo1enduCnxdWgiRkxfJlpe0R1XFA_YFSm3ffj2mBBON99lgU2vInM9OqxMlf2ctat-_IZzvmvYUOdcTVZErwN11lpQnHJ54BKicGYZrE2DNUkbv9wUma2u_gi4_O4yRhdELd7btgjFvVIo5fFoOKjAvJYmDSJ3hWsQMhVE7bQ91oUXzsdeDk22kHwu9Z3G32N-xLciRk4yN21BM" },
  { id: "p-015", slug: "oatmeal-texture-rug",     name: "Oatmeal Texture Rug",     priceInCents: 89000, currency: "USD", material: "Woven Alpaca Wool",                 category: "Rugs",     categorySlug: "rugs",     badge: "Bestseller", isAvailable: true, createdAt: "2024-09-20T00:00:00Z", imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuBmgYnlGiANqFRA7kNvb3eNWBz4zSd9VSmssbt1FbOhRAMpgoMfNFY0rds3pFhKrKYcMYuZKCDTbDZupKaaLbJ839TpJ88T2lkuBnQCQnItiHrTt_XT3B2_yXyzS0OvrcXJGtJ2Jvlhx6NKbO9Gb7enJvlqB6Man-eVWJHZPxgdPNYP48_GY1J5eK0QlJLOdGs458rTarp2XNaDFgpf98BeG2bwQLXNbQ__DYdLZxxyhwEjh36AWMUAxa_BvQFtagl_AK7GcPbcytw" },
  { id: "p-016", slug: "silk-wool-wrap",          name: "Silk & Wool Wrap",        priceInCents: 31000, currency: "USD", material: "Limited Edition",                   category: "Throws",   categorySlug: "throws",   badge: "Limited",    isAvailable: true, createdAt: "2024-12-01T00:00:00Z", imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuBXutQduBS1tDGHWgkeI-oNYfPrZbF1EcgCHRUVf7uybtvdACqtdcr0_rs-toohEZoYDKjr4eYKNaeVxmIYtIG4YvdDdK9YCiISt_GuM4qSqPiC-6fACFe4sAYTVAHbZfIimdzAx6g652YyoIuj9ExfcS7GDSVuuyC6EcdmpjOgGJ4O71E10WFOt7Ly9FJWiqWVcO1L09CK6xVbqeUjPGVuejbiC162dZuJbHUsdT5gA1hb-QKrSIsJeQXg1q1k_NqS0W3PHcV80SE" },
  { id: "p-017", slug: "ivory-boucle-throw",      name: "Ivory Boucle Throw",      priceInCents: 38000, currency: "USD", material: "Boucle Wool Blend",                 category: "Throws",   categorySlug: "throws",                        isAvailable: true, createdAt: "2024-10-10T00:00:00Z", imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuAp9f1M64Xn7ehv8vs-TAgqDSR854VE8LHranmPKuNVm6ESk_mKMjaTb9miR_DPQGVeOhhsQ9rHyXIZUUfmukmNAZuMEwTvloUZqVPp3X0D_PIKS5exY7qJhdZiwu_a07r9ACRCrKnLOAhvAXzGurkvrE2mjy3LMBHSxqY0ZLV-yiv6l2zU9P6TkaKRJJM5hPbe3XIa8VfJUkpbb52XHbGLw3IqHLnpI3h_exNYbzJ4r50MheTYP7fwtH0hN4KkVhZBoXb5iNwBMy0" },
  { id: "p-018", slug: "velvet-accent-cushion",   name: "Velvet Accent Cushion",   priceInCents: 14500, currency: "USD", material: "Belgian Velvet",                    category: "Cushions", categorySlug: "cushions", badge: "New",        isAvailable: true, createdAt: "2025-01-28T00:00:00Z", imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuBaqKjN_qh9_nvQStIndooZykKBPFIim30BT6jUiHDGxWPI40md4zPo3vwNFFWaEejLoVNETFblDSCgkjEgZuzQrEFNx4mrLWlHzpM8ATY3sff2LxnyjFYblIaQM3phvQXVH9V_nMyl2XslpRB8r2s1ne9ONmpYf1vbwPAejPs6ozB8KjZ3mlheOM1QhLJSeUpI4Tc0uGKfXSaiC3_7zbwN8Pnv1MaIR6l2KMIQR_IqY7BKJtTk-Qb6jZ05PgJPf0Jp5rZ_dl3_sOQ" },
  { id: "p-019", slug: "heritage-wool-rug",       name: "Heritage Wool Rug",       priceInCents: 120000, currency: "USD", material: "Hand-knotted New Zealand Wool",   category: "Rugs",     categorySlug: "rugs",                          isAvailable: true, createdAt: "2024-08-05T00:00:00Z", imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuAN75cqxoSnhOSjO4x7bkbnHaMOeVwOsVI2rDDFN6Xo8P4AWT7gpLr5CgwenyBEPKGEMnaCXjItzunkUdrbotuuQnZKj8-lUEIJu7T5PMfNAiEP1CCYb-R0wr4F8kDzvkG3LPnHao_CapK5mSzEm7bkZuRpUWSM5KZ5Ug0VKFGQLT8yMkeZ0FkHYJFzjzrOyY5xMt7QV2tDH97M9yr_LjvfHSUZ71VAskXnyfav2RTrSaybayD66pJ-2GOtFdQl2pyp5wBv2ott-oM" },
  { id: "p-020", slug: "cashmere-travel-wrap",    name: "Cashmere Travel Wrap",    priceInCents: 56000, currency: "USD", material: "Grade-A Mongolian Cashmere",        category: "Throws",   categorySlug: "throws",   badge: "Bestseller", isAvailable: true, createdAt: "2024-07-18T00:00:00Z", imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuAtJuPF37gE56fSewtifGK_tM7K5o-bpW354TJuzcbvCFdmiBIOZOE00Aqm26uOuxB_A9twsMVl_sgtQXBjB9uzwwKx9UBmzIbtPWm6Np1aDakw8sn5tdTFXedkDV61QToyFY5cLv6_TWSGXHBJeNg1gkyAlHltaGtYhjuTsvz7YUTtIuOFVcPbnOU_k5rc5KkA1T4jMcSGIu6MPAcPzO0tgjzkYrAI5knKGJhFEhC296icFQmHGDnLsSGU5gejYs0U3bovKmu3Btw" },
  { id: "p-021", slug: "linen-weave-cushion",     name: "Linen Weave Cushion",     priceInCents: 16500, currency: "USD", material: "European Stonewashed Linen",        category: "Cushions", categorySlug: "cushions",                      isAvailable: true, createdAt: "2024-10-30T00:00:00Z", imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuCUqBJh2dv8H2MeJxXuFow45okAbswrol6Q18bUEmdhWcTXLr5nrndXL8jl8sc9aDWTI_83itlul8p80-yDtjXKti3AgO95D2Kv5rCgpYP2mxSrPbE4De5F1o83DesDIGfwdRj34vcdJ3THJf9WbKRmROFoN6yS1CsMHTfo_I1dkpsu8GxN5qu0-LW4SG7bifXsDkdDzDJ9rPd3QQBbLmAK8agVYq6DpLvWjwrWBGy5qUgDxeb5IOjIqQYLFYiyso5fKAaQ9Gk-puA" },
  { id: "p-022", slug: "jute-wool-runner",        name: "Jute & Wool Runner",      priceInCents: 34000, currency: "USD", material: "Natural Jute & Merino",            category: "Rugs",     categorySlug: "rugs",     badge: "Limited",    isAvailable: true, createdAt: "2024-11-22T00:00:00Z", imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuBKl2gqJxZcC51zFxd4XwvCdmbVroEMa0h267Z5Zf5xq00sRgN5rPBDq5ZXYLD1nm_Dbz6iHRQokMijSrP3RLikKbc0TQIO4aVucKqUXkfCUOBCNefiwjuYEZh8aK_Pr5cssMFFYGsQUx5pySvF8CP1mkcAHwNmaB1JGSa7jHL2BCicti0BHtJUILJ0FEpY0KlPWIJJKRcrbXeUP0DwqyefUybKhHZjL3polR8I1o6XnbxWwUneJIabwj5Z1tP8t4ybwIV5LsF6rkU" },
  { id: "p-023", slug: "alpaca-chunky-throw",     name: "Alpaca Chunky Throw",     priceInCents: 49000, currency: "USD", material: "100% Baby Alpaca",                 category: "Throws",   categorySlug: "throws",   badge: "New",        isAvailable: true, createdAt: "2025-02-01T00:00:00Z", imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuB5P5jfL6RURg_w2_8tlxOjWh9aticf_LV17dMSblStiJkWbohjoEEACUR93dhAHngGT5YKnnRmiNsV6r9HRN2sO21tU7c-_MCddiLVnFm0oXQ8OgX3TVbGajCSR3aR1reX1UcULVdlOyLGOcfyXUpR5AgIYSfwqjhNYVEay62Njg_xWkR-3gwtcVFVscaKvDz6KLdA4oAy1-jZWD6L-imGnBmDMA1aLG8lUEJ7f8wJtXFcj6ztEQesDX6xP40PxSYRlZkKBKXy0dc" },
  { id: "p-024", slug: "fringed-cotton-cushion",  name: "Fringed Cotton Cushion",  priceInCents: 12000, currency: "USD", material: "Hand-tufted Cotton",               category: "Cushions", categorySlug: "cushions",                      isAvailable: true, createdAt: "2024-09-05T00:00:00Z", imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuC4fDkx8a6xYLVZrRiMOId4mF9qOq_A6fb_gZLAkgYxos3woUfgqxc9_-caD7rEhCOf7dJV9txBqLzadiIbPZzwGRYocTtE856u0HkFybIMq4b3ClwHv98Dz3rh4JA3RTqUIywoAAHKRfxW4Noai-_ehXQT40E-gh03d3Ri1JAZNh3Fbjy97pWBa2cX9mVeT_t7QFj3FSZVmN2olDS40wEAQz6rHopzUelWVU80kBD_4fgXBaMQgemF9Iau0of9qyoE4GHX1IYvrwo" },
];

export async function getProducts(query?: ProductsQuery): Promise<ProductsResponse> {
  // TODO: replace with real API call
  let data = [...MOCK_PRODUCTS];

  if (query?.category && query.category !== "All") {
    data = data.filter((p) => p.category === query.category);
  }

  if (query?.sort === "price-asc")  data.sort((a, b) => a.priceInCents - b.priceInCents);
  if (query?.sort === "price-desc") data.sort((a, b) => b.priceInCents - a.priceInCents);
  if (query?.sort === "newest")     data.sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());

  const total = data.length;
  const page  = query?.page  ?? 1;
  const limit = query?.limit ?? total;

  return {
    data: data.slice((page - 1) * limit, page * limit),
    total,
    page,
    limit,
  };
}

/** Lấy danh sách category duy nhất từ sản phẩm */
export async function getProductCategories(): Promise<string[]> {
  // TODO: replace with GET /categories/product-types
  const unique = [...new Set(MOCK_PRODUCTS.map((p) => p.category))];
  return ["All", ...unique.sort()];
}
